#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${SMARTBLOG_APP_DIR:-/workspace/SmartBlog-Live-media}"
PROFILE="${SMARTBLOG_MEDIA_PROFILE:-rtxpro6000-media}"
SECRETS_ENV="$ROOT_DIR/config/worker_secrets.conf"
BOOT_STARTED_AT="$(date +%s)"

cd "$ROOT_DIR"
export WORKER_ASSET_ROOT="${WORKER_ASSET_ROOT:-/workspace/smartblog-assets}"
mkdir -p runtime logs config "$WORKER_ASSET_ROOT" /opt/RIFE-safetensors

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [media-entrypoint] $*"; }

is_true() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

write_runtime_secrets() {
  if [[ -f "$SECRETS_ENV" ]]; then
    chmod 0600 "$SECRETS_ENV" 2>/dev/null || true
    return 0
  fi

  local keys=(
    SMARTBLOG_HF_TOKEN
    AVALIFE_HF_TOKEN
    HF_TOKEN
    HUGGING_FACE_HUB_TOKEN
    GOOGLE_API_KEY
    GEMINI_API_KEY
    AVALIFE_GEMINI_API_KEY
    SMARTBLOG_GEMINI_API_KEY
    REMOTE_EDGE_SHARED_SECRET
    REMOTE_EDGE_FILE_UPSCALE_SHARED_SECRET
    SMARTBLOG_UPSCALE_SHARED_SECRET
    WORKER_API_KEY
    VLOGME_WORKER_API_KEY
    VLOGME_WORKER_API_URL
    VLOGME_RENDER_WORKER_API_URL
    POSTPROCESSING_WORKER_TOKEN
    VLOGME_RENDER_WORKER_TOKEN
    VLOGME_RENDER_WORKER_ENABLED
    VLOGME_RENDER_API_MODE
    VLOGME_RENDER_JOB_TYPES
    VLOGME_RENDER_API_BASE
    VLOGME_RENDER_LEGACY_API_BASE
    VLOGME_RENDER_WORKER_ID
    VLOGME_RENDER_OUTPUT_SUPABASE_URL
    VLOGME_RENDER_OUTPUT_SUPABASE_SERVICE_ROLE_KEY
    VLOGME_RENDER_OUTPUT_BUCKET
    VLOGME_RENDER_OUTPUT_PREFIX
    VLOGME_RENDER_OUTPUT_PUBLIC_BASE
    SMARTBLOG_MUSETALK_SERVICE_ENABLED
    SMARTBLOG_MUSETALK_SERVICE_HOST
    SMARTBLOG_MUSETALK_SERVICE_PORT
    SMARTBLOG_MUSETALK_SERVICE_URL
    SMARTBLOG_MUSETALK_ROOT
    SMARTBLOG_MUSETALK_PYTHON
    SMARTBLOG_MUSETALK_VERSION
    SMARTBLOG_MUSETALK_USE_FLOAT16
    SMARTBLOG_MUSETALK_BATCH_SIZE
    SMARTBLOG_MUSETALK_CUDA_VISIBLE_DEVICES
    SMARTBLOG_MUSETALK_AUTO_INSTALL
    SMARTBLOG_MUSETALK_INSTALL_MMPOSE
    SMARTBLOG_MUSETALK_REQUIRE_MMPOSE
    SMARTBLOG_MUSETALK_SHARED_SECRET
    SMARTBLOG_WORKER_API_URL
    RUNPOD_POD_ID
    RUNPOD_ENDPOINT_ID
    VLOGME_MEDIA_WORKER_ID
    VLOGME_MEDIA_WORKER_PRIORITY
    VLOGME_MEDIA_REGISTRY_ENABLED
    VLOGME_MEDIA_REGISTRY_INTERVAL_SEC
    VLOGME_MEDIA_REGISTRY_TTL_SEC
    VLOGME_MEDIA_PUBLIC_BASE
    VLOGME_PUBLIC_HUNYUAN_URL
    VLOGME_PUBLIC_MMAUDIO_URL
    VLOGME_PUBLIC_FINALIZER_URL
    VLOGME_PUBLIC_UPSCALE_URL
    VLOGME_PUBLIC_MUSETALK_URL
    SMARTBLOG_MEDIA_WORKER_ID
    SMARTBLOG_MEDIA_WORKER_PRIORITY
    SMARTBLOG_MEDIA_REGISTRY_ENABLED
    SMARTBLOG_MEDIA_REGISTRY_INTERVAL_SEC
    SMARTBLOG_MEDIA_REGISTRY_TTL_SEC
    SMARTBLOG_MEDIA_PUBLIC_BASE
    SMARTBLOG_PUBLIC_HUNYUAN_URL
    SMARTBLOG_PUBLIC_MMAUDIO_URL
    SMARTBLOG_PUBLIC_FINALIZER_URL
    SMARTBLOG_PUBLIC_UPSCALE_URL
    SMARTBLOG_PUBLIC_MUSETALK_URL
  )

  local has_any=0 key tmp
  for key in "${keys[@]}"; do
    if [[ -n "${!key:-}" ]]; then
      has_any=1
      break
    fi
  done
  if [[ "$has_any" != "1" ]]; then
    log "no worker_secrets.conf and no known secret env vars; private weights or protected calls may fail"
    return 0
  fi

  tmp="$(mktemp)"
  {
    echo "# Generated by scripts/runpod_rtx6000_media_start.sh from runtime environment."
    for key in "${keys[@]}"; do
      [[ -n "${!key:-}" ]] && printf '%s=%s\n' "$key" "${!key}"
    done
  } >"$tmp"
  chmod 0600 "$tmp"
  mv -f "$tmp" "$SECRETS_ENV"
  log "wrote runtime secrets: $SECRETS_ENV"
}

export_shared_secret_aliases() {
  if [[ -z "${SMARTBLOG_UPSCALE_SHARED_SECRET:-}" && -n "${REMOTE_EDGE_FILE_UPSCALE_SHARED_SECRET:-}" ]]; then
    export SMARTBLOG_UPSCALE_SHARED_SECRET="$REMOTE_EDGE_FILE_UPSCALE_SHARED_SECRET"
  fi
  if [[ -z "${SMARTBLOG_UPSCALE_SHARED_SECRET:-}" && -n "${REMOTE_EDGE_SHARED_SECRET:-}" ]]; then
    export SMARTBLOG_UPSCALE_SHARED_SECRET="$REMOTE_EDGE_SHARED_SECRET"
  fi
}

start_sshd_if_available() {
  if ! command -v sshd >/dev/null 2>&1 && [[ ! -x /usr/sbin/sshd ]]; then
    log "sshd not installed; skipping ssh startup"
    return 0
  fi
  local public_key="${PUBLIC_KEY:-${SSH_PUBLIC_KEY:-}}"
  if [[ -z "$public_key" ]]; then
    log "PUBLIC_KEY/SSH_PUBLIC_KEY not set; skipping ssh startup"
    return 0
  fi
  mkdir -p /run/sshd /root/.ssh
  chmod 700 /root/.ssh
  printf '%s\n' "$public_key" > /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
  /usr/sbin/sshd -D -e >>"$ROOT_DIR/runtime/sshd.out" 2>&1 &
  SSHD_PID="$!"
  log "sshd started pid=$SSHD_PID"
}

prefetch_rife_if_requested() {
  if ! is_true "${SMARTBLOG_UPSCALE_PREFETCH_RIFE:-1}"; then
    return 0
  fi
  if [[ -f /opt/RIFE-safetensors/flownet.safetensors ]]; then
    return 0
  fi
  log "prefetching RIFE safetensors"
  export HF_TOKEN="${SMARTBLOG_HF_TOKEN:-${AVALIFE_HF_TOKEN:-${HF_TOKEN:-${HUGGING_FACE_HUB_TOKEN:-}}}}"
  export HUGGING_FACE_HUB_TOKEN="$HF_TOKEN"
  "$ROOT_DIR/.venv/bin/python" - <<'PY'
from huggingface_hub import snapshot_download
snapshot_download(
    repo_id="tensorforger/RIFE-safetensors",
    local_dir="/opt/RIFE-safetensors",
    local_dir_use_symlinks=False,
)
PY
}

timed_step() {
  local name="$1"
  shift
  local start end elapsed
  start="$(date +%s)"
  log "step start: $name"
  "$@"
  end="$(date +%s)"
  elapsed=$(( end - start ))
  log "step done: $name elapsed=${elapsed}s since_boot=$(( end - BOOT_STARTED_AT ))s"
}

prepare_rtx_assets() {
  local mode=""
  if is_true "${SMARTBLOG_RTX_PRESEED_ON_START:-0}"; then
    mode="verify-or-preseed"
  elif is_true "${SMARTBLOG_RTX_REQUIRE_PRESEEDED_ASSETS:-0}"; then
    mode="verify"
  else
    log "RTX asset preseed/strict verification disabled"
    return 0
  fi
  if [[ ! -x "$ROOT_DIR/scripts/preseed_rtx_media_assets.sh" ]]; then
    log "missing RTX asset preseed script"
    return 1
  fi
  bash "$ROOT_DIR/scripts/preseed_rtx_media_assets.sh" "$mode"
}

start_media_registry() {
  if ! is_true "${VLOGME_MEDIA_REGISTRY_ENABLED:-${SMARTBLOG_MEDIA_REGISTRY_ENABLED:-1}}"; then
    log "media worker registry registration disabled"
    return 0
  fi
  local python_bin="$ROOT_DIR/.venv/bin/python"
  local status="${1:-ready}"
  if [[ ! -x "$python_bin" ]]; then
    python_bin="python3"
  fi
  log "starting media worker registry heartbeat: status=$status api=${VLOGME_WORKER_API_URL:-${SMARTBLOG_WORKER_API_URL:-https://vlogme.ai/api/public/v1/worker-api}}"
  VLOGME_MEDIA_WORKER_STATUS="$status" SMARTBLOG_MEDIA_WORKER_STATUS="$status" \
    "$python_bin" "$ROOT_DIR/scripts/media_worker_registry.py" register-loop \
    >>"$ROOT_DIR/runtime/media_worker_registry_register.out" 2>&1 &
  if [[ "$status" == "ready" ]]; then
    MEDIA_REGISTRY_PID="$!"
  else
    MEDIA_REGISTRY_STARTING_PID="$!"
  fi
}

cleanup() {
  local status=$?
  set +e
  log "shutdown requested status=$status"
  if [[ -n "${MEDIA_REGISTRY_STARTING_PID:-}" ]]; then
    kill "$MEDIA_REGISTRY_STARTING_PID" 2>/dev/null || true
  fi
  if [[ -n "${MEDIA_REGISTRY_PID:-}" ]]; then
    kill "$MEDIA_REGISTRY_PID" 2>/dev/null || true
  fi
  if [[ -n "${SSHD_PID:-}" ]]; then
    kill "$SSHD_PID" 2>/dev/null || true
  fi
  bash "$ROOT_DIR/scripts/media_services.sh" stop >/dev/null 2>&1 || true
  exit "$status"
}
trap cleanup INT TERM

main() {
  log "boot root=$ROOT_DIR profile=$PROFILE git=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
  export_shared_secret_aliases
  start_sshd_if_available
  write_runtime_secrets
  bash "$ROOT_DIR/scripts/profile.sh" "$PROFILE"
  start_media_registry starting
  timed_step "prepare_rtx_assets" prepare_rtx_assets
  timed_step "prefetch_rife" prefetch_rife_if_requested

  log "starting media services"
  timed_step "media_services_start_wait" bash "$ROOT_DIR/scripts/media_services.sh" start-wait
  if [[ -n "${MEDIA_REGISTRY_STARTING_PID:-}" ]]; then
    kill "$MEDIA_REGISTRY_STARTING_PID" 2>/dev/null || true
    wait "$MEDIA_REGISTRY_STARTING_PID" 2>/dev/null || true
    unset MEDIA_REGISTRY_STARTING_PID
  fi
  start_media_registry ready
  log "media services ready; keeping container alive"

  while true; do
    sleep 30
    bash "$ROOT_DIR/scripts/media_services.sh" start >/dev/null 2>&1 || true
    bash "$ROOT_DIR/scripts/media_services.sh" status >/dev/null || true
  done
}

main "$@"
